export const Foods = [
  // Burger
  {
    id: "burger_1",
    title: "Classic Burger",
    type: "Burger",
    price: 9.99,
    img: "https://i.ibb.co/1qHtSVF/burger-thumb.jpg",
    typeIcon: "https://i.ibb.co/2McycJg/burger.png",
  },
  {
    id: "burger_2",
    title: "Cheeseburger Deluxe",
    type: "Burger",
    price: 11.99,
    img: "https://i.ibb.co/1qHtSVF/burger-thumb.jpg",
    typeIcon: "https://i.ibb.co/2McycJg/burger.png",
  },
  {
    id: "burger_3",
    title: "Double Cheeseburger",
    type: "Burger",
    price: 13.99,
    img: "https://i.ibb.co/1qHtSVF/burger-thumb.jpg",
    typeIcon: "https://i.ibb.co/2McycJg/burger.png",
  },
  {
    id: "burger_4",
    title: "Bacon Avocado Burger",
    type: "Burger",
    price: 14.99,
    img: "https://i.ibb.co/1qHtSVF/burger-thumb.jpg",
    typeIcon: "https://i.ibb.co/2McycJg/burger.png",
  },
  {
    id: "burger_5",
    title: "Veggie Burger",
    type: "Burger",
    price: 10.99,
    img: "https://i.ibb.co/1qHtSVF/burger-thumb.jpg",
    typeIcon: "https://i.ibb.co/2McycJg/burger.png",
  },

  // Pizza
  {
    id: "pizza_1",
    title: "Margherita Pizza",
    type: "Pizza",
    price: 11.99,
    img: "https://i.ibb.co/sWtsxcn/pizza-thumb.jpg",
    typeIcon: "https://i.ibb.co/xDv6j40/pizza.png",
  },
  {
    id: "pizza_2",
    title: "Pepperoni Feast",
    type: "Pizza",
    price: 14.99,
    img: "https://i.ibb.co/sWtsxcn/pizza-thumb.jpg",
    typeIcon: "https://i.ibb.co/xDv6j40/pizza.png",
  },
  {
    id: "pizza_3",
    title: "Vegetarian Pizza",
    type: "Pizza",
    price: 12.99,
    img: "https://i.ibb.co/sWtsxcn/pizza-thumb.jpg",
    typeIcon: "https://i.ibb.co/xDv6j40/pizza.png",
  },
  {
    id: "pizza_4",
    title: "Supreme Pizza",
    type: "Pizza",
    price: 15.99,
    img: "https://i.ibb.co/sWtsxcn/pizza-thumb.jpg",
    typeIcon: "https://i.ibb.co/xDv6j40/pizza.png",
  },
  {
    id: "pizza_5",
    title: "BBQ Chicken Pizza",
    type: "Pizza",
    price: 16.99,
    img: "https://i.ibb.co/sWtsxcn/pizza-thumb.jpg",
    typeIcon: "https://i.ibb.co/xDv6j40/pizza.png",
  },

  // Ramen
  {
    id: "ramen_1",
    title: "Tonkotsu Ramen",
    type: "Ramen",
    price: 14.99,
    img: "https://i.ibb.co/t3hxGjD/ramen-thumb.jpg",
    typeIcon: "https://i.ibb.co/zZvM1Sx/ramen.png",
  },
  {
    id: "ramen_2",
    title: "Miso Ramen",
    type: "Ramen",
    price: 12.99,
    img: "https://i.ibb.co/t3hxGjD/ramen-thumb.jpg",
    typeIcon: "https://i.ibb.co/zZvM1Sx/ramen.png",
  },
  {
    id: "ramen_3",
    title: "Spicy Ramen",
    type: "Ramen",
    price: 15.99,
    img: "https://i.ibb.co/t3hxGjD/ramen-thumb.jpg",
    typeIcon: "https://i.ibb.co/zZvM1Sx/ramen.png",
  },
  {
    id: "ramen_4",
    title: "Shoyu Ramen",
    type: "Ramen",
    price: 13.99,
    img: "https://i.ibb.co/t3hxGjD/ramen-thumb.jpg",
    typeIcon: "https://i.ibb.co/zZvM1Sx/ramen.png",
  },
  {
    id: "ramen_5",
    title: "Vegetarian Ramen",
    type: "Ramen",
    price: 11.99,
    img: "https://i.ibb.co/t3hxGjD/ramen-thumb.jpg",
    typeIcon: "https://i.ibb.co/zZvM1Sx/ramen.png",
  },

  // Ice Cream
  {
    id: "ice_cream_1",
    title: "Vanilla Ice Cream",
    type: "Ice Cream",
    price: 4.99,
    img: "https://i.ibb.co/yfh6Zbv/ice-cream-thumb.jpg",
    typeIcon: "https://i.ibb.co/Cn7f5kV/ice-cream.png",
  },
  {
    id: "ice_cream_2",
    title: "Chocolate Chip Cookie Dough",
    type: "Ice Cream",
    price: 5.99,
    img: "https://i.ibb.co/yfh6Zbv/ice-cream-thumb.jpg",
    typeIcon: "https://i.ibb.co/Cn7f5kV/ice-cream.png",
  },
  {
    id: "ice_cream_3",
    title: "Mint Chocolate Chip Ice Cream",
    type: "Ice Cream",
    price: 6.99,
    img: "https://i.ibb.co/yfh6Zbv/ice-cream-thumb.jpg",
    typeIcon: "https://i.ibb.co/Cn7f5kV/ice-cream.png",
  },
  {
    id: "ice_cream_4",
    title: "Strawberry Ice Cream",
    type: "Ice Cream",
    price: 5.49,
    img: "https://i.ibb.co/yfh6Zbv/ice-cream-thumb.jpg",
    typeIcon: "https://i.ibb.co/Cn7f5kV/ice-cream.png",
  },
  {
    id: "ice_cream_5",
    title: "Cookies and Cream Ice Cream",
    type: "Ice Cream",
    price: 6.49,
    img: "https://i.ibb.co/yfh6Zbv/ice-cream-thumb.jpg",
    typeIcon: "https://i.ibb.co/Cn7f5kV/ice-cream.png",
  },

  // Cupcake
  {
    id: "cupcake_1",
    title: "Chocolate Cupcake",
    type: "Cupcake",
    price: 2.99,
    img: "https://i.ibb.co/MVp2d2S/cupcake-thumb.jpg",
    typeIcon: "https://i.ibb.co/GMXnRyV/cupcake.png",
  },
  {
    id: "cupcake_2",
    title: "Red Velvet Cupcake",
    type: "Cupcake",
    price: 3.99,
    img: "https://i.ibb.co/MVp2d2S/cupcake-thumb.jpg",
    typeIcon: "https://i.ibb.co/GMXnRyV/cupcake.png",
  },
  {
    id: "cupcake_3",
    title: "Blueberry Cupcake",
    type: "Cupcake",
    price: 4.99,
    img: "https://i.ibb.co/MVp2d2S/cupcake-thumb.jpg",
    typeIcon: "https://i.ibb.co/GMXnRyV/cupcake.png",
  },
  {
    id: "cupcake_4",
    title: "Lemon Cupcake",
    type: "Cupcake",
    price: 3.49,
    img: "https://i.ibb.co/MVp2d2S/cupcake-thumb.jpg",
    typeIcon: "https://i.ibb.co/GMXnRyV/cupcake.png",
  },
  {
    id: "cupcake_5",
    title: "Strawberry Cupcake",
    type: "Cupcake",
    price: 4.49,
    img: "https://i.ibb.co/MVp2d2S/cupcake-thumb.jpg",
    typeIcon: "https://i.ibb.co/GMXnRyV/cupcake.png",
  },
];
